Setup cookbook
openstax/enki pull request #79
Opened 2022-02-07 22:27 UTC by KarinaMendez2

2022-02-09 21:57 UTC, philschatz requested changes

2022-02-09 21:57 UTC, philschatz commented on Dockerfile.common
> +ENV COOKBOOK_ROOT=$PROJECT_ROOT/cookbook
Is this environment variable used anywhere?

2022-02-09 21:57 UTC, philschatz commented on Dockerfile
> +ENV COOKBOOK_ROOT=$PROJECT_ROOT/cookbook
Is this environment variable used anywhere?

2022-02-09 21:57 UTC, philschatz commented on .env.example
> +RECIPES_ROOT=./cookbook/lib/recipes
```suggestion
RECIPES_ROOT=./cookbook
```

All of the other definitions of `RECIPES_ROOT` in this PR point to `./cookbook`. This is just an example file

2022-02-10 16:02 UTC, ckline-tryptic approved these changes

2022-02-10 16:05 UTC, merged