Sk ce 1794
openstax/enki pull request #96
Opened 2022-03-09 04:01 UTC by sparksam

@philschatz Is it okay if the scripts are located `output-producer-service/bakery` ? I was able to run the tests and build few books.

2022-03-09 18:02 UTC, therealmarv commented
Question (not related to this PR): What happens with the bakery scripts in output-producer-service / CORGI ?

2022-03-09 18:02 UTC, therealmarv approved these changes

2022-03-09 21:15 UTC, philschatz requested changes
I think most of the files in the bakery directory are no longer useful and could be excluded from the PR. I think pretty much everything except the python files in bakery/src/scripts/ are no longer used.

Also, do you know how to keep code coverage of the python files?

2022-03-16 01:42 UTC, sparksam commented
@philschatz Please review.

2022-03-16 17:24 UTC, philschatz requested changes
I am having trouble finding hte code coverage information from the bakery scripts tests. In codecov I still only see coverage for dockerfiles and build-concourse (the shell scripts and the JS) on the [sk-ce-1794 branch](https://codecov.io/gh/openstax/enki/tree/sk-ce-1794)

Also, these files used by anything in the repo?

- bakery/src/scripts/Dockerfile
- bakery/src/scripts/*.sh and maybe most of *.json

2022-03-28 19:00 UTC, philschatz commented on test/test-step-10.bash
> +pip install "../output-producer-service/bakery/src/scripts/.[test]"
```suggestion
if [[ $CI = '' && $VIRTUAL_ENV = '' ]]; then
   echo "Activate a virtualenv before running this"
   exit 1
fi

pip install "../output-producer-service/bakery/src/scripts/.[test]"
```

Will this install packages into the system version of python?

2022-03-30 15:12 UTC, philschatz approved these changes

2022-04-01 05:25 UTC, merged